### ISSUE TITLE
conversation_not_found error in client.website.update_conversation_metas since ugpgrading to 1.1.5

### ISSUE THREAD

**Issue by reederz** [crisp-im/python-crisp-api#11]
We started getting conversation_not_found error in `client.website.update_conversation_metas` since upgrading to 1.1.5 . 1.1.6 is also affected. Downgrading back to 1.1.4 fixes the issue.

**Comment by baptistejamin** [comment]
Hi there! Can you please send us a screenshot of this?

**Comment by reederz** [comment]
Sorry, after a little bit of testing, it seems that it's our fault.

We used to check for error type by looking into `str(route_error)` but it seems you changed the structure of route error now. Before it was:
```
RouteError(reason)
```

Now it's:
```
RouteError(error_dict)
```

We'll adjust our code accordingly.

**Comment by baptistejamin** [comment]
Hi!
Got it, let us know if you have any questions :)
