### ISSUE TITLE
Is Real time messaging handle in python wrapper?

### ISSUE THREAD

**Issue by hadifar** [crisp-im/python-crisp-api#3]
Hi,
How can I listen to user's messages? I need to implement something similar to [this](https://help.crisp.chat/en/article/how-to-send-messages-from-my-backend-n94aue/) thread. I want to know this feature handled in python or not?

Best,
Amir

**Comment by mywaystar** [comment]
What we suggest is using web hook instead for Python. https://help.crisp.chat/en/article/how-to-use-webhooks-itsagz/ <https://help.crisp.chat/en/article/how-to-use-webhooks-itsagz/>
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 12 Jun 2018, at 13:06, Amir Hadifar <notifications@github.com> wrote:

Hi,
How can I listen to user's messages? I need to implement something similar to this <https://help.crisp.chat/en/article/how-to-send-messages-from-my-backend-n94aue/> thread. I want to know this feature handled in python or not?
