### ISSUE TITLE
Cannot install crisp-api using pip

### ISSUE THREAD

**Issue by MrBin99** [crisp-im/python-crisp-api#6]
Hi,
I plan to use the Crisp API lib in Python but I cannot install it with pip.

I think the issue is due to the last pull request who has not been pushed to the pip servers.
So in the `setup.py` the `encoding='utf-8'` is not present and pip during the install cannot read the README.md file : `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 226: character maps to <undefined>`.

Can you update pip server with the latest code.

Thanks !

**Comment by Spoonrad** [comment]
Hello team,

Following my pull request you updated the repo but not the pip package. Could you please make an update to the pip package? I'd rather not have a public git URL in my pip requirements file.

**Comment by valeriansaliou** [comment]
Hello there, tried publishing on PyPI, but it's now failing as README formatting in Markdown has been deprecated. I'll need to convert to the proper README format and then upload; for now I'm unable to upload the package.

Can you please install it from Git instead?

**Comment by valeriansaliou** [comment]
Opened an issue to track this #7

**Comment by Spoonrad** [comment]
Hi Valerian,

 

No worries, that is currently what I’m doing, it is not urgent but preferred. 😊

Thanks for your reactivity!

**Comment by eliottvincent** [comment]
Hello there, your changes have been taken into account with release 1.1.3 :)
Published on PyPI: https://pypi.org/project/crisp-api/
