### ISSUE TITLE
Convert README from Markdown to reStructuredText

### ISSUE THREAD

**Issue by valeriansaliou** [crisp-im/python-crisp-api#7]
When trying to publishing to PyPI:

```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

The README must be converted to the new README format in order to resume our ability to publish packages.

**Comment by eliottvincent** [comment]
fixed with https://github.com/crisp-im/python-crisp-api/commit/f9098da0785c47b94d67d93ebcf08278ad181a1d
