### ISSUE TITLE
check_people_profile_exists function throws JSONDecodeError, Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mahmudulshuvo** [crisp-im/python-crisp-api#8]
Hi I'm trying to find the people id for an existing contact in the crisp. So I called this api like this.

`response = client.website.check_people_profile_exists(settings.CRISP_WEBSITE_ID, 'test@crisp.chat')`

But is throwing a JSONDecodeError exception. What I'm doing wrong?

**Comment by p-maks** [comment]
Looking at the apis this return HTTP 200 without any body when profile found, 404 otherwise.
so not sure if api should return any body for `result = req.json()` or this needs to handle differently

**Comment by eliottvincent** [comment]
Hello there! Issue fixed with release v1.1.3: https://github.com/crisp-im/python-crisp-api/releases/tag/v1.1.3
Updated on PyPI too: https://pypi.org/project/crisp-api/
